# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobaokewap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jdcookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cookies', models.CharField(max_length=2500)),
            ],
        ),
    ]
